# Generated by Django 5.1.7 on 2025-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_currency', models.CharField(max_length=3)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receiver_currency', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Request', 'Request')], default='Sent', max_length=10)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Completed', max_length=20)),
            ],
        ),
    ]
